WebProject/WebProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),


    # User functionality
    path('', include('users.urls')),
    path('', include('cluster.urls')),

    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WebProject/cluster/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static

from .views import *

from cluster.api import ClusterAPI, FileDocumentView

app_name = 'cluster'

urlpatterns = [

    path('', indexView, name="Index"),
    path('cluster/', cluster_list, name="cluster"),
    path('addCluster/', create_cluster_with_urls, name="addCluster"),
    path('search/', searchPageView, name="search"),

    path('api/clusterlist/', ClusterAPI.as_view()),
    path('api/file/', FileDocumentView.as_view({'get': 'list'})),




] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WebProject/users/urls.py

from django.urls import path, re_path
from django.contrib.auth import views as auth_views
import users.views as userView

from users.api import UserAPI

app_name = 'users'

urlpatterns = [

    # User API
    path('api/users/', UserAPI.as_view()),




]

WebProject/cluster/models.py
# Create your models here.
from django.conf import settings
from django.db import models


class Cluster(models.Model):

    name = models.CharField(max_length=255)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,)
    crawled = models.BooleanField(default=False)

    class Meta:
        db_table = 'Cluster'

    def __str__(self):
        return self.name


class Url(models.Model):

    url = models.CharField(max_length=10000)
    depth = models.CharField(max_length=10000)

    crawling = (
        ('ALL', "ALL"),
        ('DOC', 'DOC'),
        ('PDF', 'PDF'),
        ('PPT', 'PPT'),
        ('HTML', 'HTML'),
        ('NON-HTML', 'NON-HTML'),
    )
    crawling_strategy = models.CharField(max_length=100, choices=crawling)

    cluster = models.ForeignKey(
        Cluster,
        related_name='Urls', on_delete=models.SET_NULL,
        null=True)

    class Meta:
        db_table = 'URL'

    def __str__(self):
        return self.url


class File(models.Model):
    filecluster = models.CharField(max_length=1000, default=0)
    mainurl = models.CharField(max_length=1000)
    fileurl = models.CharField(max_length=10000)
    filetype = models.CharField(max_length=255)
    content = models.TextField(max_length=100000000000000000)

    class Meta:
        db_table = 'File'

    def __str__(self):
        return self.fileurl

WebProject/cluster/forms.py
from django import forms
from django.forms import (formset_factory, modelformset_factory)

from .models import (Url, Cluster, File)

#Create File model form
class FileModelForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ['fileurl', 'filetype', 'content', 'mainurl', 'filecluster']
#Create Cluster Form

class ClusterModelForm(forms.ModelForm):

    class Meta:
        model = Cluster
        fields = ('name', )
        labels = {
            'name': 'Cluster name'
        }
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter cluster name'
            }
            )
        }

#Create Searchform
class SearchForm(forms.Form):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['usercluster'].queryset = Cluster.objects.filter(
            owner=user)

    usercluster = forms.ModelChoiceField(
        queryset=None, widget=forms.Select(attrs={'class': "form-control"}), required=True)
    keyword = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control"}))


UrlFormset = modelformset_factory(
    Url,
    fields=('url', 'depth', 'crawling_strategy'),
    extra=1,
    widgets={'url': forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter Url'
    }), 'depth': forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter depth'
    }), 'crawling_strategy': forms.Select(attrs={
        'class': 'form-control',
        'placeholder': 'Enter desired strategy'
    })
    }
)

WebProject/cluster/views.py

# Create your views here.
from django.conf import settings
from django.core.mail import send_mail
import pandas as pd
from typing import Reversible
from django.db.models import query
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import get_user
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

import json
from .forms import *
from .models import *

import threading

import mimetypes

import requests
from urllib.parse import urlparse, urljoin
from bs4 import BeautifulSoup
from time import time, sleep

from tika import parser
import tika
tika.initVM()

# api
apiurl = "http://127.0.0.1:8000/api/file?format=json&"

json_list = {}


# Check user logged in or not
def indexView(request):
    if request.user.is_authenticated:
        return redirect('cluster:cluster')
    else:
        return render(request, 'login.html')


# Create cluster with urls

def create_cluster_with_urls(request):
    user = request.user
    template_name = 'addcluster.html'
    if request.method == 'GET':
        clusterform = ClusterModelForm(request.GET or None)
        urlformset = UrlFormset(queryset=Url.objects.none())
    elif request.method == 'POST':
        clusterform = ClusterModelForm(request.POST)
        urlformset = UrlFormset(request.POST)
        if clusterform.is_valid() and urlformset.is_valid():

            obj = clusterform.save(commit=False)
            obj.owner = request.user
            obj.crawled = False
            obj.save()
            for form in urlformset:

                newurl = form.save(commit=False)
                newurl.cluster = obj
                newurl.save()
            # checkcluster(user)
            t1 = threading.Thread(target=checkcluster, args=(user,))
            t1.start()
            return redirect('cluster:cluster')
    return render(request, template_name, {
        'clusterform': clusterform,
        'urlformset': urlformset,
    })


def download(request):
    df = pd.DataFrame(json_list)
    print(df)

# search page


def searchPageView(request):
    searchform = SearchForm(user=request.user)
    if request.method == 'GET':
        searchform = SearchForm(request.GET, user=request.user)
        if searchform.is_valid():
            keyword = searchform.cleaned_data.get("keyword")
            cluster = searchform.cleaned_data.get("usercluster")
            headers = {
                'Authorization': 'Token e697bea2c349db8c61a55accf6c0546db5de0dd8'}
            url = apiurl+"search=" + keyword + "&filecluster="+str(cluster.id)
            response = requests.get(url, headers=headers).json()
            diction = response
            json_list = response
            df = pd.DataFrame(json_list)
            print(df)
            text_list = []
            list = []
            for i in range(len(diction)):
                text = diction[i]['content']
                text_list.append(abbreviate(text, 150))
                # print(diction)
                # list = diction[i]['content'].split()
                # for j in range(len(list)):
                #     if list[j].lower() == keyword.lower():
                #         text_list.append('.......... '+list[j-3] + " " + list[j-2] + " " + list[j-1] + " " +
                #                          list[j] + " " + list[j+1] + " " + list[j+2] + " " + list[j+3] + " ..........")
                #         print('.......... '+list[j-3] + " " + list[j-2] + " " + list[j-1] + " " +
                #               list[j] + " " + list[j+1] + " " + list[j+2] + " " + list[j+3] + " ..........")
                #         break
            try:
                for i in range(len(diction)):
                    # try:Nat
                    diction[i]['content'] = text_list[i]
                    print(diction[i]['content'])

            except:
                print("Error")
            return render(request, 'search.html', {'searchform': searchform, 'file_list': diction, 'keyword': keyword, 'text_list': text_list})
    return render(request, 'search.html', {'searchform': searchform, })

# cluster page


def cluster_list(request):
    cluster_list = Cluster.objects.all().filter(owner=request.user)
    diction = {'title': 'Cluster', 'cluster_list': cluster_list}
    return render(request, 'cluster.html', context=diction)


def abbreviate(text, max):
    if(len(text) > max):
        text = text[0:max] + "......."
    return text


# Check crawling strategy


def sendUrlformset(urllist):
    for newurl in urllist:
        global internal_urls
        internal_urls = set()
        global external_urls
        external_urls = set()
        global all
        all = set()

        crawl(newurl.url, int(newurl.depth))
        internal_urls.update(external_urls)
        all.update(internal_urls)
        if newurl.crawling_strategy == "PDF":
            for u in all:
                if u.endswith('.pdf'):
                    print(u)
                    try:
                        Fileform = FileModelForm()

                        obj = Fileform.save(commit=False)
                        obj.fileurl = u
                        obj.filecluster = str(newurl.cluster.id)
                        obj.mainurl = str(newurl.id)
                        parsed = parser.from_file(u)
                        obj.content = parsed["content"].replace("\n", " ")
                        obj.filetype = "PDF"
                        obj.save()
                    except:
                        print("No data found")

        elif newurl.crawling_strategy == "DOC":
            for u in all:
                if u.endswith('.doc') or u.endswith('.docx'):
                    print(u)
                    try:
                        Fileform = FileModelForm()
                        obj = Fileform.save(commit=False)
                        obj.fileurl = u
                        obj.filecluster = str(newurl.cluster.id)
                        obj.mainurl = str(newurl.id)
                        parsed = parser.from_file(u)
                        obj.content = parsed["content"].replace("\n", " ")
                        obj.filetype = "DOC"
                        obj.save()
                    except:
                        print("No data found")

        elif newurl.crawling_strategy == "HTML":
            for u in all:
                if u.endswith('.html'):
                    print(u)
                    try:
                        Fileform = FileModelForm()
                        obj = Fileform.save(commit=False)
                        obj.fileurl = u
                        obj.filecluster = str(newurl.cluster.id)
                        obj.mainurl = str(newurl.id)
                        parsed = parser.from_file(u)
                        obj.content = parsed["content"].replace("\n", " ")
                        obj.filetype = "HTML"
                        obj.save()
                    except:
                        print("No data found")

        elif newurl.crawling_strategy == "PPT":
            for u in all:
                if u.endswith('.ppt') or u.endswith('.pptx'):
                    print(u)
                    try:
                        Fileform = FileModelForm()
                        obj = Fileform.save(commit=False)
                        obj.fileurl = u
                        obj.filecluster = str(newurl.cluster.id)
                        obj.mainurl = str(newurl.id)
                        parsed = parser.from_file(u)
                        obj.content = parsed["content"].replace("\n", " ")
                        obj.filetype = "PPT"
                        obj.save()
                    except:
                        print("No data found")

        elif newurl.crawling_strategy == "NON-HTML":
            for u in all:
                if u.endswith('.doc') or u.endswith('.ppt') or u.endswith('.pdf') or u.endswith('.docx') or u.endswith('.pptx'):
                    print(u)
                    try:
                        Fileform = FileModelForm()
                        obj = Fileform.save(commit=False)
                        obj.fileurl = u
                        obj.filecluster = str(newurl.cluster.id)
                        obj.mainurl = str(newurl.id)
                        parsed = parser.from_file(u)
                        obj.content = parsed["content"].replace("\n", " ")
                        obj.filetype = "NON-HTML"
                        obj.save()
                    except:
                        print("No data found")

        elif newurl.crawling_strategy == "ALL":
            for u in all:
                if u.endswith('.doc') or u.endswith('.ppt') or u.endswith('.html') or u.endswith('.pdf') or u.endswith('.docx') or u.endswith('.pptx'):
                    print(u)
                    try:
                        Fileform = FileModelForm()
                        obj = Fileform.save(commit=False)
                        obj.fileurl = u
                        obj.filecluster = str(newurl.cluster.id)
                        obj.mainurl = str(newurl.id)
                        parsed = parser.from_file(u)
                        obj.content = parsed["content"].replace("\n", " ")
                        obj.filetype = "ALL"
                        obj.save()
                    except:
                        print("No data found")

        else:
            print("NOT VALID")


total_urls_visited = 0


def is_valid(url):

    # Checks whether 'url' is a valid URL.

    parsed = urlparse(url)
    return bool(parsed.netloc) and bool(parsed.scheme)

# get all website link



WebProject/templates/addcluster.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="bg-image vh-100" style="background-image: url('/static/white_bg.png');background-size: cover;">
    <div class="container ">
        <div class="row " style="padding-top: 60px;height: 120px;">
            <div class=" col-2 col-sm-1">
                <img src="/static/logo.png" style="width: 100%; float: left;" alt="">
            </div>
            <div class="col-8 col-sm-10 text-left align-self-center">

                <i class="fas fa-user-circle fa-2x"
                    style="color: #3785E0;vertical-align: middle; justify-content: center;margin-right: 5px;"></i>

                <span style="font-size: larger;vertical-align: middle;font-weight: 600;">
                    {{ user.email }}
                </span>

            </div>
            <div class="col-2 col-sm-1 text-right align-self-center" style="text-align: right;">
                <a href="{% url 'logout' %}"><button type=" button" class="btn btn-danger ">Logout</button></a>
            </div>

        </div>
    </div>
    <div class=" container">


        <div class="row" style="margin-top: 60px;">

            <div class=" col-1"></div>
            <div class="col-4 text-right" style="border-radius: 10px;">
                <a href="{% url 'cluster:cluster' %}"><button type="button" class="btn btn-lg btn-primary w-100"
                        style="color: white;">Cluster</button></a>
            </div>
            <div class=" col-2">
            </div>
            <div class="col-4 text-left" style="border-radius: 10px;">
                <a href="{% url 'cluster:search' %}"><button type="button" class="btn btn-lg btn-primary w-100"
                        style="background-color: white;color: black;">Search</button></a>
            </div>
            <div class="col-1"></div>
        </div>

        <div class="row" style="padding-top: 60px;">

            <div class="bg-image overflow-auto"
                style="background: white; height: 600px;border-radius: 10px;box-shadow: rgba(9, 30, 66, 0.25) 0px 4px 8px -2px, rgba(9, 30, 66, 0.08) 0px 0px 0px 1px;">
                <div class="container">
                    <div class="row " style="padding-top: 50px;">
                        <form class="form-horizontal" method="POST" action="">
                            {% csrf_token %}
                            <div class="row spacer" style="margin-bottom: 40px;">
                                <div class="col-2">
                                    <h4>{{clusterform.name.label}}</h4>
                                </div>
                                <div class="col-10">
                                    <div class="input-group">
                                        {{clusterform.name}}
                                    </div>
                                </div>
                            </div>
                            {{ urlformset.management_form }}
                            {% for form in urlformset %}
                            <div class="row form-row spacer" style="margin-top: 10px;">
                                <div class="col-2">
                                    <h4>{{form.url.label}}</h4>
                                </div>
                                <div class="col-10">
                                    <div class="input-group">
                                        {{form.url}}
                                        {{form.depth}}
                                        {{form.crawling_strategy}}
                                        <div class="input-group-append">
                                            <button class="btn btn-success add-form-row">+</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="row spacer" style="margin-top: 20px;margin-bottom: 50px;">
                                <div class="col-10">

                                </div>
                                <div class="col-2">
                                    <button type="submit" class="btn btn-block btn-primary w-100">Create</button>
                                </div>
                            </div>
                        </form>





                    </div>

                </div>
            </div>
        </div>



    </div>

</div>

</div>
{% else %}
<div class="alert alert-danger" role="alert">
    Your attempt to view this page is <a href="/" class="alert-link">Unauthorized</a>.
</div>
{% endif %}
{% endblock content %}

{% block custom_js %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script type="text/javascript">
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
            var name = $(this).attr('name')
            if (name) {
                name = name.replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({ 'for': forValue });
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        var conditionRow = $('.form-row:not(:last)');
        conditionRow.find('.btn.add-form-row')
            .removeClass('btn-success').addClass('btn-danger')
            .removeClass('add-form-row').addClass('remove-form-row')
            .html('-');
        return false;
    }
    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }
    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

</script>
{% endblock %}

WebProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href={% static 'css/style.css' %}>
    <script src="https://kit.fontawesome.com/6f1880a575.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    <script src="https://cdn.lordicon.com/libs/mssddfmo/lord-icon-2.1.0.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@800&display=swap" rel="stylesheet">
    <title>FileBook</title>
    <link rel="icon" href="/static/logo.png" type="image/x-icon">




    {% block styles %}
    {% endblock %}
</head>

<body class="body">
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
    {% block custom_js %}{% endblock %}
</body>

</html>

WebProject/templates/cluster.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="bg-image vh-100" style="background-image: url('/static/white_bg.png');background-size: cover;">
    <div class="container ">
        <div class="row" style="padding-top: 20px;">
            <div class=" col-2 col-sm-1">
                <img src="/static/logo.png" style="width: 100%; float: left;" alt="">
            </div>
        </div>
        <div class="row " style="margin-top: 20px;">

            <div class="col-10 col-sm-10 text-left align-self-center">
                <i class="fas fa-user-circle fa-2x"
                    style="color: #3785E0;vertical-align: middle; justify-content: center;margin-right: 5px;"></i>

                <span style="font-size: larger;vertical-align: middle;font-weight: 600;">
                    {{ user.email }}
                </span>

            </div>
            <div class="col-2 col-sm-2 text-right align-self-center" style="text-align: right;">
                <a href="{% url 'logout' %}"><button type=" button" class="btn btn-danger ">Logout</button></a>
            </div>

        </div>
    </div>
    <div class=" container">


        <div class="row" style="margin-top: 60px;">

            <div class=" col-1"></div>
            <div class="col-4 text-right" style="border-radius: 10px;"><a href="{% url 'cluster:cluster' %}"><button
                        type="button" class="btn btn-lg btn-primary w-100" style="color: white;">Cluster</button></a>

            </div>
            <div class=" col-2">
            </div>
            <div class="col-4 text-left" style="border-radius: 10px;"><a href="{% url 'cluster:search' %}"><button
                        type="button" class="btn btn-lg btn-primary w-100"
                        style="background-color: white;color: black;">Search</button></a>

            </div>
            <div class="col-1"></div>
        </div>

        <div class="row" style="padding-top: 60px;">

            <div class="bg-image overflow-auto"
                style="background: white; height: 600px;border-radius: 10px;box-shadow: rgba(9, 30, 66, 0.25) 0px 4px 8px -2px, rgba(9, 30, 66, 0.08) 0px 0px 0px 1px;">
                <div class="container">
                    <div class="row " style="padding-top: 50px;">

                        <div class="col-1 "></div>
                        <div class="col-5  text-left">
                            <h3>My Clusters</h3>
                        </div>
                        <div class="col-5  text-right" style="text-align: right;">
                            <a href="{% url 'cluster:addCluster' %}">
                                <button type="button" class="btn btn-primary" style="width: 50%;">Add</button></a>
                        </div>
                        <div class="col-1 "></div>

                    </div>
                    <div class="row" style="margin-top:50px">
                        <div class="col-1"></div>
                        <div class="col-10">
                            <table>
                                {% for cluster in cluster_list %}
                                <tr>
                                    <button type="button" class="btn btn-clusterlist  btn-lg"
                                        style="width: 100%;text-align: left;margin-bottom: 30px;">{{cluster.name}}</button>
                                </tr>
                                {% endfor %}
                            </table>

                        </div>
                        <div class="col-1"></div>


                    </div>

                </div>
            </div>
        </div>



    </div>

</div>

</div>
{% else %}
<div class="alert alert-danger" role="alert">
    Your attempt to view this page is <a href="/" class="alert-link">Unauthorized</a>.
</div>
{% endif %}
{% endblock content %}

WebProject/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% block styles %}
{% load socialaccount %}

{% endblock %}
{% block content %}
{% if user.is_authenticated %}
{% else %}
<div class="container-fluid">
    <div class="row">
        <div id="image01" class="col-md-8 vh-100"
            style="background-image: url('/static/Blue_BG.png');background-size: cover;">

            <div class="container d-flex h-100 ">


                <h1 class="row justify-content-center align-self-center w-100"
                    style="font-family: 'Dosis', sans-serif;color:white;font-size: 60px;">
                    Searching for any file?<br>
                    Dont know where to find?<br> FileBook is here to help..
                </h1>
            </div>
        </div>
        <div class=" col-md-4 p-4  left_side" style="height: 100vh;">
            <img src="/static/logo.png" style="width: 20%; float: right;" alt="">

            <div style="margin-top: 150px;">
                <h2 style="margin-bottom: 200px;">Login</h2>


                <a href="{% provider_login_url 'google' %}"><button class="btn btn-light w-100  "><img
                            src="/static/icon_google.png" class="image03"><b>Login
                            with Google</b>
                    </button></a>




            </div>


        </div>
    </div>
</div>
</div>
{% endif %}

{% endblock content %}